### ISSUE TITLE
[Suggestion] There should be a `--nix` option to mount the `/nix` directory in distrobox

### ISSUE THREAD

**Issue by dnkmmr69420** [89luca89/distrobox#1019]
**Is your feature request related to a problem? Please describe.**
I don't always want `/nix` to be mounted with no option to create a container with `/nix` not to be mounted

**Describe the solution you'd like**
I was thinking that if a user wants `/nix` to be mounted inside the container, the `--nix` option would be used. By default `/nix` should not be mounted. I was thinking that this would give users a choice if they want `/nix` to be mounted inside the container. `--nix` option would be used for `distrobox create` when the user wants `/nix` to be mounted in the container. `distrobox assemble` could have something similar.

**Comment by tdolega** [comment]
Why would you want to have `/nix` mounted inside the container? Using host binaries doesn't make any sense in my understanding. And why only `--nix`. What if Ubuntu user wants to use host binaries, then add option `--ubuntu`?

**Comment by dnkmmr69420** [comment]
nix is mounted if installed and there is no option to disable mounting of `/nix`

**Comment by tdolega** [comment]
It was mounted in the past, but it should't be as you pointed out. It was fixed [in this commit](https://github.com/89luca89/distrobox/commit/5dd7b00e3f095e1976c0e2aa4f972efdcd6f4f3a), but unfortunately there was no new version released (builded) since this commit. So you can wait or build master yourself.

**Comment by dnkmmr69420** [comment]
> It was mounted in the past, but it should't be as you pointed out. It was fixed [in this commit](https://github.com/89luca89/distrobox/commit/5dd7b00e3f095e1976c0e2aa4f972efdcd6f4f3a), but unfortunately there was no new version released (builded) since this commit. So you can wait or build master yourself.

I did not know that. Good to know.

**Comment by vigneshpai2003** [comment]
I am using nixos-unstable and my containers still have the /nix directory. I created the ubuntu container after updating distrobox to 1.7.1.0 and restarting my system
```
$ distrobox version
distrobox: 1.7.1.0

$ distrobox enter ubuntu
@ubuntu:/home/vignesh$ ls /
bin  boot  dev  etc  home  lib  lib32  lib64  libx32  media  mnt  nix  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```
