### ISSUE TITLE
[Error] Unicode characters are broken on Debian/Ubuntu containers

### ISSUE THREAD

**Issue by kaanyalova** [89luca89/distrobox#1045]
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
Unicode characters don't render properly on Debian/Ubuntu containers.   
I also tried Arch Linux and Fedora containers but they don't have this issue.

Running ls with some unicode named files looks like this

 
![Ekran Görüntüsü - 2023-11-08 19-30-59](https://github.com/89luca89/distrobox/assets/76952012/b3165433-c97f-4220-acb7-c7cb9721fa94)

Typing unicode characters is also broken it looks like this,
![Ekran Görüntüsü - 2023-11-08 19-41-33](https://github.com/89luca89/distrobox/assets/76952012/8fcae40d-3e23-4677-a60d-dadb9a2bf468)

**To Reproduce**
Create a Debian/Ubuntu container

Try to type or display a unicode character

**Expected behavior**
Unicode characters should look normal.

**Logs**
[verbose.txt](https://github.com/89luca89/distrobox/files/13299162/verbose.txt)
[podman-logs.txt](https://github.com/89luca89/distrobox/files/13299175/podman-logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? `Podman`
 - Which version or podman, docker or lilipod? `4.7.0`
 - Which version of distrobox? `1.5.0.2`
 - Which host distribution? `Fedora 39`
 - How did you install distrobox? `dnf`

**Comment by 89luca89** [comment]
Thanks @kaanyalova it seems like this depends on a wrongly set LANG variable

This is already fixed in git version
If that doesn't work, please feel free to repoen the issue

**Comment by briner** [comment]
I do not know what actually to provide you:

outside of distrobox (within silverblue), I got:
```bash
echo $LANG
  # fr_FR.UTF-8

ls mod*
  # modèle-caucus.ott
```

within the distrobox
```bash
distrobox enter deb12

echo $LANG
  # fr_FR.UTF-8

ls mod*
  # 'mod'$'\303\250''le-caucus.ott'
```

**Comment by kaanyalova** [comment]
I still have the same issue on bash and zsh, but when i use fish it somehow works

distrobox version `1.6.0.1`
