### ISSUE TITLE
[Error] 1.7.0 breaks lilipod support

### ISSUE THREAD

**Issue by polak14** [89luca89/distrobox#1261]
**Describe the bug**
I can't use lilipod with distrobox 1.7.0 anymore `distrobox-create` fails to create containers and `distrobox-enter` fails to enter any existing containers.

`distrobox create -n test -i archlinux` returns `Creating 'test' using image archlinux   2024/03/07 00:24:38 unknown flag: --pids-limit`
`distrobox enter test` on an existing container returns `2024/03/07 00:26:33 no such object: [test]`

**To Reproduce**
`distrobox create -n test -i archlinux`
`distrobox enter test` on an existing container

**Expected behavior**
The container 'test' is successfully created or entered

**Logs**
[log.txt](https://github.com/89luca89/distrobox/files/14517493/log.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? lilipod
 - Which version or podman, docker or lilipod? v0.0.1
 - Which version of distrobox? 1.7.0
 - Which host distribution? Arch Linux
 - How did you install distrobox? tried both pacman and source

**Additional context**
When using podman everything works as expected.
When using distrobox 1.6.0 everything works as expected with the lilipod backend.

**Comment by Meister1593** [comment]
Experiencing same issue
`Creating 'arch-alvr' using image docker.io/archlinux/archlinux:latest   2024/03/08 20:30:07 unknown flag: --pids-limit`

**Comment by Meister1593** [comment]
Also if you remove that flag from distroboxc-create, there's still an issue, commit d409ce4d5bdd8f4d61a14e0e9afcc79b3d974361 breaks inspection for lilipod containers (bellow log on that commit, previous commit 5201a2d works):

```
+ '[' -z arch-alvr ']'
+ '[' '!' -t 0 ']'
+ '[' '!' -t 1 ']'
+ headless=1
+ case "${container_manager}" in
+ container_manager=lilipod
+ command -v lilipod
+ '[' 1 -ne 0 ']'
+ container_manager='lilipod --log-level debug'
+ '[' 0 -ne 0 ']'
+ container_home=/home/plyshka
+ container_path=/home/plyshka/tmp/ALVR-Distrobox-Linux-Guide/installation-lilipod/bin:/home/plyshka/tmp/ALVR-Distrobox-Linux-Guide/installation-lilipod/bin:/home/plyshka/tmp/ALVR-Distrobox-Linux-Guide/installation-lilipod/bin:/home/plyshka/.volta/bin:/home/plyshka/.local/bin:/home/plyshka/bin:/home/plyshka/.cargo/bin:/bedrock/cross/pin/bin:/bedrock/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/games:/usr/games:/home/plyshka/.local/share/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/bedrock/cross/bin
+ unshare_groups=0
+ container_status=unknown
++ lilipod --log-level debug inspect --type container --format 'container_status={{.State.Status}};
        unshare_groups={{ index .Config.Labels "distrobox.unshare_groups" }};
        {{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}container_home={{slice . 5 | printf "%q"}};{{end}}{{end}}
        {{range .Config.Env}}{{if slice . 0 5 | eq "PATH="}}container_path={{slice . 5 | printf "%q"}}{{end}}{{end}}' arch-alvr
2024/03/08 21:03:20 no such object: [arch-alvr]
+ eval ''
+ '[' 0 -ne 0 ']'
+ '[' unknown = unknown ']'
+ '[' 0 -eq 1 ']'
+ printf 'Create it now, out of image %s? [Y/n]: ' registry.fedoraproject.org/fedora-toolbox:39
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:39? [Y/n]: + read -r response
```

**Comment by Meister1593** [comment]
On that note, lilipod should get regression testing (basically same tests as podman, but on lilipod. Otherwise regression might happen again in future and without user tests it will be only found out in such issues.

**Comment by 89luca89** [comment]
Thanks for reporting, fixed with v0.0.2

Regression tests will be added in the future indeed :+1:

**Comment by Meister1593** [comment]
> Also if you remove that flag from distrobox-create, there's still an issue, commit [d409ce4](https://github.com/89luca89/distrobox/commit/d409ce4d5bdd8f4d61a14e0e9afcc79b3d974361) breaks inspection for lilipod containers (bellow log on that commit, previous commit [5201a2d](https://github.com/89luca89/distrobox/commit/5201a2d2e547bf1fe6a89cfdbe29274096b95be8) works):
> 
> ```
> + '[' -z arch-alvr ']'
> + '[' '!' -t 0 ']'
> + '[' '!' -t 1 ']'
> + headless=1
> + case "${container_manager}" in
> + container_manager=lilipod
> + command -v lilipod
> + '[' 1 -ne 0 ']'
> + container_manager='lilipod --log-level debug'
> + '[' 0 -ne 0 ']'
> + container_home=/home/plyshka
> + container_path=/home/plyshka/tmp/ALVR-Distrobox-Linux-Guide/installation-lilipod/bin:/home/plyshka/tmp/ALVR-Distrobox-Linux-Guide/installation-lilipod/bin:/home/plyshka/tmp/ALVR-Distrobox-Linux-Guide/installation-lilipod/bin:/home/plyshka/.volta/bin:/home/plyshka/.local/bin:/home/plyshka/bin:/home/plyshka/.cargo/bin:/bedrock/cross/pin/bin:/bedrock/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/games:/usr/games:/home/plyshka/.local/share/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/bedrock/cross/bin
> + unshare_groups=0
> + container_status=unknown
> ++ lilipod --log-level debug inspect --type container --format 'container_status={{.State.Status}};
>         unshare_groups={{ index .Config.Labels "distrobox.unshare_groups" }};
>         {{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}container_home={{slice . 5 | printf "%q"}};{{end}}{{end}}
>         {{range .Config.Env}}{{if slice . 0 5 | eq "PATH="}}container_path={{slice . 5 | printf "%q"}}{{end}}{{end}}' arch-alvr
> 2024/03/08 21:03:20 no such object: [arch-alvr]
> + eval ''
> + '[' 0 -ne 0 ']'
> + '[' unknown = unknown ']'
> + '[' 0 -eq 1 ']'
> + printf 'Create it now, out of image %s? [Y/n]: ' registry.fedoraproject.org/fedora-toolbox:39
> Create it now, out of image registry.fedoraproject.org/fedora-toolbox:39? [Y/n]: + read -r response
> ```

This is still an issue, even on latest version, lilipod doesn't work, it was unrelated to first comment
Should i create another issue or is fine to continue here?
