### ISSUE TITLE
[Error] apt-get sometime crashes the container

### ISSUE THREAD

**Issue by chitao1234** [89luca89/distrobox#1289]
**Describe the bug**
If I use `apt-get` to install a lot of packages in one go, the container might crash with exit code `137`, `podman inspect` shows `"ExitCode": 1`

**To Reproduce**
```shell
$ distrobox create -n test -i ubuntu:jammy
$ distrobox enter test
$ sudo apt-get install qemu-system
```
qemu-system has a lot of dependencies, so it's quite likely the container would crash.

**Expected behavior**
The packages is installed normally, as it is in a normal podman container.

**Logs**
[create.log](https://github.com/89luca89/distrobox/files/14622456/create.log)
[enter.log](https://github.com/89luca89/distrobox/files/14622454/enter.log)
[podman-logs.log](https://github.com/89luca89/distrobox/files/14622455/podman-logs.log)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 podman
 - Which version or podman, docker or lilipod?
 podman version 4.9.3
 - Which version of distrobox?
distrobox: 1.7.0.1
 - Which host distribution?
EndeavourOS (Archlinux based)
 - How did you install distrobox?
With pacman

**Additional context**
The problem does NOT occur if I changed the `sleep 15` to `sleep 150` in [distrobox-init](https://github.com/89luca89/distrobox/blob/7a56b6e899574c428cdfd3c228198d639149c1a8/distrobox-init#L2175)

**Comment by jakubiszon26** [comment]
I have really simmilar issue but it's pacman that causes distrobox to crash

**Comment by Lesabotsy** [comment]
Tried both Ubuntu and Arch, both crash on package install/update.

**Comment by chitao1234** [comment]
Changing the sleep duration to 150 lowers the probability of the crash happening, and the patch #1296 should fix this reliably.

**Comment by espentrydal** [comment]
> Changing the sleep duration to 150 lowers the probability of the crash happening, and the patch #1296 should fix this reliably.

I tried to apply the changes in the patch manually, it did not make any difference for me. `sleep 150` seems to fix it though.

**Comment by 6cdh** [comment]
That patch fixed it for me. I applied it manually and recreate my dev container because the crash corrupted pacman database.

**Comment by RodoMa92** [comment]
Thanks for the temporary patch. I'll test it shortly and report back. Sadly my pacman database was killed in the process and I also had to rebuild the container.

**Comment by RodoMa92** [comment]
Nope, #1296 doesn't fix it for me. The shell still die with 137 and podman inspect has an error return code of 1. I'll test the longer sleep command shortly again.

**Comment by RodoMa92** [comment]
Yeah, same error message:

```
/usr/bin/entrypoint: line 2154: /usr/sbin/findmnt: cannot execute: required file not found
Error: An error occurred
```

**Comment by chitao1234** [comment]
I'm trying to replicate how the error message `cannot execute: required file not found` occurred. Would you mind telling me how the container was built?

**Comment by RodoMa92** [comment]
> I'm trying to replicate how the error message `cannot execute: required file not found` occurred. Would you mind telling me how the container was built?

`distrobox-create --unshare-netns --image ghcr.io/ublue-os/bazzite-arch --name arch -Y` then just 'paru' to update the arch container inside it. It will fail to install the initial packages since the image has a glibc outdated since it's failing to build for a while, just retry to enter it again to get in without the additional requested packages.

**Comment by markob94** [comment]
I have the same issue. 
Distrobox Ubuntu-latest, wanted to install one app : _sudo apt install proton-vpn-gnome-desktop_ and during install, on cca 67% terminal just crashed ( it close). distrobox: 1.7.0.1 .

**Comment by schoentoon** [comment]
Patch #1296 instantly fixed this issue for me.

**Comment by FSMaxB** [comment]
I worked around it for now by downgrading back to `1.6.0.1`

**Comment by 89luca89** [comment]
Fixed with PR #1296 thanks @chitao1234 for the PR and the investigation!

**Comment by rgbmew** [comment]
This also still happens for me, on multiple host distros, using multiple containers. It happens almost every time I install something via `yay` in my arch container, and crashes all of the apps the container is currently running. Please re-open!

**Comment by 89luca89** [comment]
I canno reproduce the bug anymore @rgbmew are you sure you're on 1.7.1?

![Screenshot from 2024-03-28 16-02-37](https://github.com/89luca89/distrobox/assets/598882/28b33428-a485-496e-8774-8104b4483df0)

In this case I'm installing a very big set of package (`libgtk3*` just to exhagerate) and it worked fine

**Comment by rgbmew** [comment]
My bad!!! I misread 1.7.0.1 as 1.7.1!! Thanks so much for catching that :pensive:

**Comment by RodoMa92** [comment]
> Sadly it's not fixed for me, log attached while using the latest git release [podmanlog.txt](https://github.com/89luca89/distrobox/files/14748879/podmanlog.txt) This issue should be reopened IMO.

Yeah, it seems I also can't reproduce it any more. Odd.
