### ISSUE TITLE
[Feature] NixOS support

### ISSUE THREAD

**Issue by AtilaSaraiva** [89luca89/distrobox#33]
Hello!

I'm currently using the Arch Linux container and can't use sudo, given the following error:
```
Files % /usr/bin/sudo su
sudo: PAM account management error: Authentication service cannot retrieve authentication info
sudo: a password is required
```
I tried running passwd but I don't know my user password inside the container too. While we're at it, is there a way to have the binaries at /usr/bin/ at my path so I don't have to write the full path all the time?

As for the log, here it is:
```
++ '[' 0 -ne 0 ']'
+ '[' '!' -f /run/.containerenv ']'
+ '[' -z 1001 ']'
+ '[' -z /home/atila ']'
+ '[' -z atila ']'
+ '[' -z 1001 ']'
++ basename /run/current-system/sw/bin/zsh
+ shell_pkg=zsh
+ command -v mount
/usr/sbin/mount
+ command -v passwd
/usr/sbin/passwd
+ command -v sudo
/usr/sbin/sudo
+ command -v useradd
/usr/sbin/useradd
+ command -v usermod
/usr/sbin/usermod
+ command -v zsh
/usr/sbin/zsh
+ HOST_MOUNTS_RO='/etc/machine-id /var/lib/flatpak /var/lib/systemd/coredump /var/log/journal'
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/etc/machine-id /etc/machine-id ro
+ source_dir=/run/host/etc/machine-id
+ target_dir=/etc/machine-id
+ mount_flags=ro
+ '[' -d /run/host/etc/machine-id ']'
+ '[' -f /run/host/etc/machine-id ']'
+ '[' -d /run/host/etc/machine-id ']'
+ '[' -f /run/host/etc/machine-id ']'
+ touch /etc/machine-id
+ '[' ro = '' ']'
+ mount_flags=rslave
+ mount --rbind -o rslave /run/host/etc/machine-id /etc/machine-id
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/lib/flatpak /var/lib/flatpak ro
+ source_dir=/run/host/var/lib/flatpak
+ target_dir=/var/lib/flatpak
+ mount_flags=ro
+ '[' -d /run/host/var/lib/flatpak ']'
+ '[' -d /run/host/var/lib/flatpak ']'
+ mkdir -p /var/lib/flatpak
+ '[' ro = '' ']'
+ mount_flags=rslave
+ mount --rbind -o rslave /run/host/var/lib/flatpak /var/lib/flatpak
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/lib/systemd/coredump /var/lib/systemd/coredump ro
+ source_dir=/run/host/var/lib/systemd/coredump
+ target_dir=/var/lib/systemd/coredump
+ mount_flags=ro
+ '[' -d /run/host/var/lib/systemd/coredump ']'
+ '[' -d /run/host/var/lib/systemd/coredump ']'
+ mkdir -p /var/lib/systemd/coredump
+ '[' ro = '' ']'
+ mount_flags=rslave
+ mount --rbind -o rslave /run/host/var/lib/systemd/coredump /var/lib/systemd/coredump
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/log/journal /var/log/journal ro
+ source_dir=/run/host/var/log/journal
+ target_dir=/var/log/journal
+ mount_flags=ro
+ '[' -d /run/host/var/log/journal ']'
+ '[' -d /run/host/var/log/journal ']'
+ mkdir -p /var/log/journal
+ '[' ro = '' ']'
+ mount_flags=rslave
+ mount --rbind -o rslave /run/host/var/log/journal /var/log/journal
+ return 0
+ HOST_MOUNTS='/media /run/media /run/udev/data /mnt /var/mnt /run/systemd/journal /run/libvirt /var/lib/libvirt'
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/media /media rw
+ source_dir=/run/host/media
+ target_dir=/media
+ mount_flags=rw
+ '[' -d /run/host/media ']'
+ '[' -f /run/host/media ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/media /run/media rw
+ source_dir=/run/host/run/media
+ target_dir=/run/media
+ mount_flags=rw
+ '[' -d /run/host/run/media ']'
+ '[' -f /run/host/run/media ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/udev/data /run/udev/data rw
+ source_dir=/run/host/run/udev/data
+ target_dir=/run/udev/data
+ mount_flags=rw
+ '[' -d /run/host/run/udev/data ']'
+ '[' -d /run/host/run/udev/data ']'
+ mkdir -p /run/udev/data
+ '[' rw = '' ']'
+ mount_flags=rslave
+ mount --rbind -o rslave /run/host/run/udev/data /run/udev/data
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/mnt /mnt rw
+ source_dir=/run/host/mnt
+ target_dir=/mnt
+ mount_flags=rw
+ '[' -d /run/host/mnt ']'
+ '[' -f /run/host/mnt ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/var/mnt /var/mnt rw
+ source_dir=/run/host/var/mnt
+ target_dir=/var/mnt
+ mount_flags=rw
+ '[' -d /run/host/var/mnt ']'
+ '[' -f /run/host/var/mnt ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/systemd/journal /run/systemd/journal rw
+ source_dir=/run/host/run/systemd/journal
+ target_dir=/run/systemd/journal
+ mount_flags=rw
+ '[' -d /run/host/run/systemd/journal ']'
+ '[' -d /run/host/run/systemd/journal ']'
+ mkdir -p /run/systemd/journal
+ '[' rw = '' ']'
+ mount_flags=rslave
+ mount --rbind -o rslave /run/host/run/systemd/journal /run/systemd/journal
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/libvirt /run/libvirt rw
+ source_dir=/run/host/run/libvirt
+ target_dir=/run/libvirt
+ mount_flags=rw
+ '[' -d /run/host/run/libvirt ']'
+ '[' -f /run/host/run/libvirt ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/var/lib/libvirt /var/lib/libvirt rw
+ source_dir=/run/host/var/lib/libvirt
+ target_dir=/var/lib/libvirt
+ mount_flags=rw
+ '[' -d /run/host/var/lib/libvirt ']'
+ '[' -f /run/host/var/lib/libvirt ']'
+ return 0
+ '[' -d /usr/lib/rpm/macros.d/ ']'
+ grep -q 'Defaults !fqdn' /etc/sudoers
+ grep -q 'atila ALL = (root) NOPASSWD:ALL' /etc/sudoers
+ grep -q atila /etc/group
+ id atila
uid=1001(atila) gid=1001(users) groups=1(wheel),57(networkmanager),1001(users)
+ passwd --delete atila
passwd: password expiry information changed.
+ passwd --delete root
passwd: password expiry information changed.
+ mkdir -p /home/atila/.local/share/themes
+ mkdir -p /home/atila/.local/share/icons
+ chown 1001:1001 /home/atila/.local/share/themes
+ chown 1001:1001 /home/atila/.local/share/icons
+ mount_bind /run/host/usr/share/themes /home/atila/.local/share/themes rw
+ source_dir=/run/host/usr/share/themes
+ target_dir=/home/atila/.local/share/themes
+ mount_flags=rw
+ '[' -d /run/host/usr/share/themes ']'
+ '[' -f /run/host/usr/share/themes ']'
+ return 0
+ mount_bind /run/host/usr/share/icons /home/atila/.local/share/icons rw
+ source_dir=/run/host/usr/share/icons
+ target_dir=/home/atila/.local/share/icons
+ mount_flags=rw
+ '[' -d /run/host/usr/share/icons ']'
+ '[' -f /run/host/usr/share/icons ']'
+ return 0
+ printf 'container_setup_done\n'
container_setup_done
```

Thx for your time and your wonderful work!

Átila.

**Comment by 89luca89** [comment]
Hi @AtilaSaraiva thanks for the report!

can you give me some information about the host and which version of `distrobox` you're running?

As you can see from the log here:

```
+ grep -q 'Defaults !fqdn' /etc/sudoers
+ grep -q 'atila ALL = (root) NOPASSWD:ALL' /etc/sudoers
```

Your user is directly added to sudoers with NOPASSWD, so it should not 

Also it inherits the PATH from the host's environment so it should automatically pick /usr/bin

I've just tried now with an `archlinux:latest` container on ubuntu and on fedora hosts and it's working as intended (using the last released version 1.1.2)

**Comment by AtilaSaraiva** [comment]
Of course! I'm running distrobox from the main branch, which makes me think that I have to test the release version. I grabbed the scripts from yesterday so it shouldn't be much of a difference but still. 

As for the host, here are the info:
OS: NixOS 21.11 (Porcupine) x86_64
Kernel: 5.15.3-zen1
WM: sway
CPU: Intel Xeon E5-2650 v3 (20) @ 3.000GHz
GPU: AMD ATI Radeon RX 580
Memory: 5348MiB / 15850MiB

I'll test the release version and let you know.

**Comment by 89luca89** [comment]
You can just do `podman stop container_name; podman rm container_name` and you're good to go :smile: 

Also I see NixOS, It's not in the tested operating systems list, so I wonder if something is not compatible, if the release version of distrobox does not fix the issue, I'll try setting up a NixOS VM to check if there is any incompatibility :+1:

**Comment by AtilaSaraiva** [comment]
Yeah, I've just tested the release version and the same thing happened. Nevertheless, it is strange that NixOS is not compatible. I will have to study your scripts to check if there it is dependent on the distro being FHS, and if there is any hope in adapting it.

**Comment by 89luca89** [comment]
Yea I've set up a NixOS VM right now, still trying to set up rootless podman, any useful tips? I'm completely new to nix :sweat_smile: 

Anyway yes I do quite some mounts in `create` and env passing in `enter`, and then a lot of `bind mounts` in `init` so if the file system hierarchy is non-standard, It **could** break stuff

that said, all this should have nothing to do with sudo which is all in the container part, so I'm suspecting something else is going on probably?

Can I have the output also of `create` and again the output of `enter` with the new `main` branch?

**Comment by AtilaSaraiva** [comment]
Nice! Yeah, I can give u my whole config file if u want, but the basic setup for podman is through this options:
```
  virtualisation = {
    podman = {
      enable = true;
      dockerCompat = true;
    };
  };
```
I will download the current branch and give you the logs. Thx!

**Comment by AtilaSaraiva** [comment]
Here is the create log:
```
~ % distrobox-create --image registry.fedoraproject.org/fedora-toolbox:35 --name fedora-toolbox-35
Image not found.
Do you want to pull the image now?[y/n] y
Trying to pull registry.fedoraproject.org/fedora-toolbox:35...
Getting image source signatures
Copying blob ddd5af41e96b skipped: already exists
Copying blob 146f1bef8f31 done
Copying config ab8bc106d4 done
Writing manifest to image destination
Storing signatures
ab8bc106d4a710a7a27c538762864610467b3559f80b413d30e0a1bfcfe272a5
b5c6cd5544be3fd66b2608deb10718cd803fa5cafa9276c07a8d22f6730bf6ef
Distrobox 'fedora-toolbox-35' successfully created.
To enter, run:
	distrobox-enter --name fedora-toolbox-35
```

Here is the output of the distrobox-enter command:
```
~ % distrobox-create --image registry.fedoraproject.org/fedora-toolbox:35 --name fedora-toolbox-35
Image not found.
Do you want to pull the image now?[y/n] y
Trying to pull registry.fedoraproject.org/fedora-toolbox:35...
Getting image source signatures
Copying blob ddd5af41e96b skipped: already exists
Copying blob 146f1bef8f31 done
Copying config ab8bc106d4 done
Writing manifest to image destination
Storing signatures
ab8bc106d4a710a7a27c538762864610467b3559f80b413d30e0a1bfcfe272a5
b5c6cd5544be3fd66b2608deb10718cd803fa5cafa9276c07a8d22f6730bf6ef
Distrobox 'fedora-toolbox-35' successfully created.
To enter, run:
	distrobox-enter --name fedora-toolbox-35
~ % distrobox-enter --name fedora-toolbox-35
Starting container fedora-toolbox-35
run this command to follow along:
	podman logs -f fedora-toolbox-35
...................................................................................................................................................
done!
Error: executable file `/run/current-system/sw/bin/zsh` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found

An error occurred
```

and here is the podman log for the enter command

```
~ % podman logs -f fedora-toolbox-35
+ '[' '!' -f /run/.containerenv ']'
+ '[' -z 1001 ']'
+ '[' -z /home/atila ']'
+ '[' -z atila ']'
+ '[' -z 1001 ']'
++ basename /run/current-system/sw/bin/zsh
+ shell_pkg=zsh
+ command -v mount
/usr/bin/mount
+ command -v passwd
/usr/bin/passwd
+ command -v sudo
/usr/bin/sudo
+ command -v useradd
/usr/sbin/useradd
+ command -v usermod
/usr/sbin/usermod
+ command -v zsh
+ command -v apk
+ command -v apt-get
+ command -v dnf
/usr/bin/dnf
+ dnf install -y zsh passwd procps-ng shadow-utils sudo util-linux
Fedora 35 - x86_64                              677 kB/s |  61 MB     01:32
Fedora 35 openh264 (From Cisco) - x86_64        1.8 kB/s | 2.5 kB     00:01
Fedora Modular 35 - x86_64                      1.1 MB/s | 2.6 MB     00:02
Fedora 35 - x86_64 - Updates                    496 kB/s |  16 MB     00:32
Fedora Modular 35 - x86_64 - Updates            402 kB/s | 992 kB     00:02
Package passwd-0.80-11.fc35.x86_64 is already installed.
Package procps-ng-3.3.17-3.fc35.x86_64 is already installed.
Package shadow-utils-2:4.9-3.fc35.x86_64 is already installed.
Package sudo-1.9.7p2-2.fc35.x86_64 is already installed.
Package util-linux-2.37.2-1.fc35.x86_64 is already installed.
Dependencies resolved.
================================================================================
 Package        Architecture      Version               Repository         Size
================================================================================
Installing:
 zsh            x86_64            5.8-6.fc35            fedora            2.9 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 2.9 M
Installed size: 7.6 M
Downloading Packages:
zsh-5.8-6.fc35.x86_64.rpm                       1.3 MB/s | 2.9 MB     00:02
--------------------------------------------------------------------------------
Total                                           978 kB/s | 2.9 MB     00:03
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1
  Installing       : zsh-5.8-6.fc35.x86_64                                  1/1
  Running scriptlet: zsh-5.8-6.fc35.x86_64                                  1/1
  Verifying        : zsh-5.8-6.fc35.x86_64                                  1/1

Installed:
  zsh-5.8-6.fc35.x86_64

Complete!
+ HOST_MOUNTS_RO='/etc/machine-id /var/lib/flatpak /var/lib/systemd/coredump /var/log/journal'
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/etc/machine-id /etc/machine-id ro
+ source_dir=/run/host/etc/machine-id
+ target_dir=/etc/machine-id
+ mount_flags=ro
+ '[' -d /run/host/etc/machine-id ']'
+ '[' -f /run/host/etc/machine-id ']'
+ '[' -d /run/host/etc/machine-id ']'
+ '[' -f /run/host/etc/machine-id ']'
+ touch /etc/machine-id
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/etc/machine-id /etc/machine-id
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/lib/flatpak /var/lib/flatpak ro
+ source_dir=/run/host/var/lib/flatpak
+ target_dir=/var/lib/flatpak
+ mount_flags=ro
+ '[' -d /run/host/var/lib/flatpak ']'
+ '[' -d /run/host/var/lib/flatpak ']'
+ mkdir -p /var/lib/flatpak
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/var/lib/flatpak /var/lib/flatpak
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/lib/systemd/coredump /var/lib/systemd/coredump ro
+ source_dir=/run/host/var/lib/systemd/coredump
+ target_dir=/var/lib/systemd/coredump
+ mount_flags=ro
+ '[' -d /run/host/var/lib/systemd/coredump ']'
+ '[' -d /run/host/var/lib/systemd/coredump ']'
+ mkdir -p /var/lib/systemd/coredump
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/var/lib/systemd/coredump /var/lib/systemd/coredump
+ return 0
+ for host_mount_ro in ${HOST_MOUNTS_RO}
+ mount_bind /run/host/var/log/journal /var/log/journal ro
+ source_dir=/run/host/var/log/journal
+ target_dir=/var/log/journal
+ mount_flags=ro
+ '[' -d /run/host/var/log/journal ']'
+ '[' -d /run/host/var/log/journal ']'
+ mkdir -p /var/log/journal
+ '[' ro = '' ']'
+ mount --rbind -o ro /run/host/var/log/journal /var/log/journal
+ return 0
+ HOST_MOUNTS='/media /run/media /run/udev/data /mnt /var/mnt /run/systemd/journal /run/libvirt /var/lib/libvirt'
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/media /media rw
+ source_dir=/run/host/media
+ target_dir=/media
+ mount_flags=rw
+ '[' -d /run/host/media ']'
+ '[' -f /run/host/media ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/media /run/media rw
+ source_dir=/run/host/run/media
+ target_dir=/run/media
+ mount_flags=rw
+ '[' -d /run/host/run/media ']'
+ '[' -f /run/host/run/media ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/udev/data /run/udev/data rw
+ source_dir=/run/host/run/udev/data
+ target_dir=/run/udev/data
+ mount_flags=rw
+ '[' -d /run/host/run/udev/data ']'
+ '[' -d /run/host/run/udev/data ']'
+ mkdir -p /run/udev/data
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/run/udev/data /run/udev/data
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/mnt /mnt rw
+ source_dir=/run/host/mnt
+ target_dir=/mnt
+ mount_flags=rw
+ '[' -d /run/host/mnt ']'
+ '[' -f /run/host/mnt ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/var/mnt /var/mnt rw
+ source_dir=/run/host/var/mnt
+ target_dir=/var/mnt
+ mount_flags=rw
+ '[' -d /run/host/var/mnt ']'
+ '[' -f /run/host/var/mnt ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/systemd/journal /run/systemd/journal rw
+ source_dir=/run/host/run/systemd/journal
+ target_dir=/run/systemd/journal
+ mount_flags=rw
+ '[' -d /run/host/run/systemd/journal ']'
+ '[' -d /run/host/run/systemd/journal ']'
+ mkdir -p /run/systemd/journal
+ '[' rw = '' ']'
+ mount --rbind -o rw /run/host/run/systemd/journal /run/systemd/journal
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/run/libvirt /run/libvirt rw
+ source_dir=/run/host/run/libvirt
+ target_dir=/run/libvirt
+ mount_flags=rw
+ '[' -d /run/host/run/libvirt ']'
+ '[' -f /run/host/run/libvirt ']'
+ return 0
+ for host_mount in ${HOST_MOUNTS}
+ mount_bind /run/host/var/lib/libvirt /var/lib/libvirt rw
+ source_dir=/run/host/var/lib/libvirt
+ target_dir=/var/lib/libvirt
+ mount_flags=rw
+ '[' -d /run/host/var/lib/libvirt ']'
+ '[' -f /run/host/var/lib/libvirt ']'
+ return 0
+ '[' -d /usr/lib/rpm/macros.d/ ']'
+ net_mounts=
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/mnt:/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/var/mnt:/mnt:/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/run/systemd/journal:/var/mnt:/mnt:/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/run/libvirt:/run/systemd/journal:/var/mnt:/mnt:/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/var/lib/libvirt:/run/libvirt:/run/systemd/journal:/var/mnt:/mnt:/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/dev:/var/lib/libvirt:/run/libvirt:/run/systemd/journal:/var/mnt:/mnt:/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/proc:/dev:/var/lib/libvirt:/run/libvirt:/run/systemd/journal:/var/mnt:/mnt:/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/sys:/proc:/dev:/var/lib/libvirt:/run/libvirt:/run/systemd/journal:/var/mnt:/mnt:/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ for net_mount in ${HOST_MOUNTS_RO} ${HOST_MOUNTS} '/dev' '/proc' '/sys' '/tmp'
+ net_mounts=/tmp:/sys:/proc:/dev:/var/lib/libvirt:/run/libvirt:/run/systemd/journal:/var/mnt:/mnt:/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id:
+ net_mounts=/tmp:/sys:/proc:/dev:/var/lib/libvirt:/run/libvirt:/run/systemd/journal:/var/mnt:/mnt:/run/udev/data:/run/media:/media:/var/log/journal:/var/lib/systemd/coredump:/var/lib/flatpak:/etc/machine-id
+ cat
+ grep -q 'Defaults !fqdn' /etc/sudoers
+ printf 'Defaults !fqdn\n'
+ grep -q 'atila ALL = (root) NOPASSWD:ALL' /etc/sudoers
+ printf '%s ALL = (root) NOPASSWD:ALL\n' atila
+ grep -q atila /etc/group
+ groupadd --force --gid 1001 atila
+ id atila
uid=1001(atila) gid=1001(users) groups=1(wheel),57(networkmanager),1001(users)
+ passwd --delete atila
Removing password for user atila.
passwd: Success
+ passwd --delete root
passwd: Note: deleting a password also unlocks the password.
Removing password for user root.
passwd: Success
+ mkdir -p /home/atila/.local/share/themes
+ mkdir -p /home/atila/.local/share/icons
+ chown 1001:1001 /home/atila/.local/share/themes
+ chown 1001:1001 /home/atila/.local/share/icons
+ mount_bind /run/host/usr/share/themes /home/atila/.local/share/themes rw
+ source_dir=/run/host/usr/share/themes
+ target_dir=/home/atila/.local/share/themes
+ mount_flags=rw
+ '[' -d /run/host/usr/share/themes ']'
+ '[' -f /run/host/usr/share/themes ']'
+ return 0
+ mount_bind /run/host/usr/share/icons /home/atila/.local/share/icons rw
+ source_dir=/run/host/usr/share/icons
+ target_dir=/home/atila/.local/share/icons
+ mount_flags=rw
+ '[' -d /run/host/usr/share/icons ']'
+ '[' -f /run/host/usr/share/icons ']'
+ return 0
+ printf 'container_setup_done\n'
container_setup_done
+ sleep infinity
```

**Comment by 89luca89** [comment]
Can you run the `enter` and the `create` part with `--verbose`? Se we can investigate what is happening

One problem I see is that it is exporting $SHELL as a non-standard path that the runtime could not find., can you try setting $SHELL to `/bin/sh` or any other shell with a standard path?

**Comment by 89luca89** [comment]
Also now I understand why you have to specify /usr/bin for stuff inside the container
NixOS does not use those directories at all in the PATH, and that is inherited by the container, which being a normal FHS distro it will have a completely different layout

**Comment by 89luca89** [comment]
@AtilaSaraiva I've just merged `docker` support for distrobox

Tested on NixOS with docker and it worked, but needs a couple of workarounds:

- `distrobox-create` worls as intended
- `distrobox-enter` needs  you to pass the `-e` or `--` argument and force a normal path to shell (/bin/bash for example)
- you need to set up a `$PATH` that works for an FHS distro, or it will not find any commands

I used

`distrobox-create --image registry.fedoraproject.org/fedora-toolbox:35 --name fedora-toolbox-35`
`distrobox-create --image archlinux:latest --name arch-test`

then

`distrobox-enter --name fedora-toolbox-35 -- /bin/bash -l`
`distrobox-enter --name arch-test -- /bin/bash -l`

And inside, I set the PATH with

`export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

And it worked :smile: also `sudo` worked too, probably it is related to the bugfix introduced with one of the latest merge [HERE](https://github.com/89luca89/distrobox/commit/9fa59dc40568a06da265735b556100e19ffcc9ae)

It was a typo, but never noticed as probably NixOS is the first distro where uid and gid are not the same (at least in my installation :smile: )

**Comment by AtilaSaraiva** [comment]
Hello gain,
Thank you for all your dedication to this issue. This PATH solution managed to resolve the issue with having to write full paths to binaries, but I still don't have sudo here :/. Could share your config so I could try to compare it with mine and try to find out the reason why?
The output of using sudo still is 
```
[atila@arch-test ~]$ sudo pacman -Syu
sudo: PAM account management error: Authentication service cannot retrieve authentication info
sudo: a password is required
```

**Comment by 89luca89** [comment]
Cool so is it working now using podman or docker?

I think there are 2 main point of divergence here:

- distrobox-enter needs you to pass the -e or -- argument and force a normal path to shell (/bin/bash for example)
          - here I could do some checks on the $SHELL and if it's not in PATH I can default to `/bin/sh` that would improve the situation
          
- you need to set up a $PATH that works for an FHS distro, or it will not find any commands
          - here I can't do much :) This is an user configuration part, but I could add it to the notes in the OS support table

**Comment by 89luca89** [comment]
@AtilaSaraiva I've created a branch for this, and I've implemented a simple normalization of the default shell
Right now this works on NixOS if we add this to the user profile:

`export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

So that we append the normal FHS paths to the NixOS own paths.

**Comment by AtilaSaraiva** [comment]
Great man! I will start working on the derivation. It might be possible to set the PATH in the derivation but I'm not sure. I'll update you on the progress!

**Comment by AtilaSaraiva** [comment]
Sorry luca I was a bit stuck at work, do you still want me to test? I will do it first thing tomorrow!

**Comment by 89luca89** [comment]
Absolutely no problems 😄 No rush! I'll wait your feedback 👍

**Comment by AtilaSaraiva** [comment]
Hey Luca! I tested here with the fedora image, using the scripts from the last git commit in the feature branch and it worked even without the $PATH modification! This is great, thx for all the work you've done :D

**Comment by 89luca89** [comment]
Cool stuff today I'll merge it :+1:

**Comment by AtilaSaraiva** [comment]
@89luca89 , I managed to finally find some time to package distrobox into NixOS. The [PR](https://github.com/NixOS/nixpkgs/pull/160251) is still being reviewed but it will in all likelihood be merged.

**Comment by 89luca89** [comment]
Super :smile:
