### ISSUE TITLE
[Suggestion] Add support for Crystal Linux, and/or provide documentation on how to make a proper distrobox image

### ISSUE THREAD

**Issue by orowith2os** [89luca89/distrobox#351]
**Is your feature request related to a problem? Please describe.**
Partially, just a request to add a distribution to the list of supported guests, along with adding documentation on making a Distrobox image.

[Crystal Linux](https://github.com/crystal-linux) is based on Arch, and adds a few packages on top of it to make it a more user-friendly experience. They host their own Docker image/file, available at https://github.com/crystal-linux/crystal-docker

**Comment by 89luca89** [comment]
>  adding documentation on making a Distrobox image.

https://distrobox.privatedns.org/distrobox_custom.html

> support

seems you already had it working right? If it's arch based I think we can already assume it's working 
right now I'm downloading it, but compared to arch the image size is really big, so adding it to the supported list, and so tested automatically every time we merge something in `main`, will become a really big problem

**Comment by orowith2os** [comment]
ah, thanks for linking that page. I must've skipped over it.
Yes, I do have it working currently, although it's a bit screwey with shells that aren't bash running on the host. I'm hoping to get this fixed before adding it to the supported by distrobox list. 

tbf it *is* an Arch ISO with a bunch of tools preinstalled, so it makes sense that it would be larger.

**Comment by 89luca89** [comment]
> tbf it is an Arch ISO with a bunch of tools preinstalled, so it makes sense that it would be larger.

Yea that's why I was thinking if including it explicitly in the compatibility list is the right move
If arch works, this works
And being a big download it can hinder a lot the various CI runs (and last time my account was suspended so I might not take the risk)

**Comment by orowith2os** [comment]
If you don't mind me asking, why would including Crystal in the compatibility list affect so much? Would it not just be possible to say it's verified, and link to the docker image for it? Isn't this what's done for all the other distrobox-supported guest distros?

**Comment by 89luca89** [comment]
Nothing inherently against 
I just thought the much bigger size could be a problem during ci runs
But let's add it and if there are problems I'm planning to leave GitHub actions anyway 

If you want to open a pr to add it to the compatibility list you're welcome or I'll do it next time I'm at PC

**Comment by orowith2os** [comment]
I've created a PR that adds Crystal, and some information about the current state of using it with shells that are not Bash

**Comment by 89luca89** [comment]
As stated in the comment of the PR, that shell thing should not be a problem, and from my testing it is working as intended.
If it does not work, it should be a bug in `distrobox-init` more than Crystal Linux

**Comment by orowith2os** [comment]
hm, I'll give it another try and see if it works.

**Comment by orowith2os** [comment]
Yeah, it's not working for me over here on Fish: 
![image](https://user-images.githubusercontent.com/93224879/179637114-00b80702-4da7-433a-a341-b5c795c8dd42.png)

**Comment by 89luca89** [comment]
That's a problem with Crystal
you have `/bin/apt` as a placeholder that says: 
`Sorry for the bother, we don't use apt on Crystal, we use ame! Please use that instead!`

So init tries to use apt to install stuff (as it detects it)
Not sure at this point I can add Crystal to the compatibility list as pacman won't be ever called if apt is detected

**Comment by orowith2os** [comment]
I've made a change to the Dockerfile to remove the other package manager placeholder commands, so now it works fine. I'll remove the warning from the PR so you can merge it.

**Comment by 89luca89** [comment]
Very good thanks!

**Comment by orowith2os** [comment]
The devs for Crystal are also working on separating the placeholder commands into a separate package, so it won't be as jank of a solution in the future. Thanks for approving the PR and adding Crystal!

**Comment by 89luca89** [comment]
Hi @orowith2os 

Images are failing the package installation again
this is blocking my CI

```
pacman -Sy --noconfirm bash bc curl diffutils findutils less ncurses pinentry procps-ng shadow sudo util-linux wget vte-common
warning: bash-5.1.016-1 is up to date -- reinstalling
warning: curl-7.84.0-2 is up to date -- reinstalling
warning: diffutils-3.8-1 is up to date -- reinstalling
warning: findutils-4.9.0-1 is up to date -- reinstalling
warning: less-1:590-1 is up to date -- reinstalling
warning: ncurses-6.3-3 is up to date -- reinstalling
warning: pinentry-1.2.0-1 is up to date -- reinstalling
warning: procps-ng-3.3.17-1 is up to date -- reinstalling
warning: shadow-4.11.1-1 is up to date -- reinstalling
warning: sudo-2.0-1 is up to date -- reinstalling
warning: util-linux-2.38-1 is up to date -- reinstalling
warning: wget-1.21.3-1 is up to date -- reinstalling
warning: dependency cycle detected:
warning: ncurses will be installed before its bash dependency
warning: dependency cycle detected:
warning: ncurses will be installed before its bash dependency
warning: dependency cycle detected:
warning: ncurses will be installed before its bash dependency
warning: dependency cycle detected:
warning: ncurses will be installed before its bash dependency
warning: dependency cycle detected:
warning: ncurses will be installed before its bash dependency
error: sudo: signature from "Build-A-Package Workshop 2: Electric Boogaloo (Beep2 Boop2!) <null@getcryst.al>" is invalid
error: failed to commit transaction (invalid or corrupted package)
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
```

**Comment by 89luca89** [comment]
For now I'm reverting the change in order for the CI to complete successfully
I'll do further testing in the future

**Comment by orowith2os** [comment]
hm, I'm a bit interested in what the CI job is for. Is it just to test compatibility with distrobox, and make sure it works?

back to the topic at hand, it seems like a standard dependency loop to me, possibly fixed by updating *everything* rather than just those specific packages? I can also try rebuilding it on my system in a bit, and see if it has that same issue you're having.

**Comment by not-my-segfault** [comment]
Hi, Project Lead of @crystal-linux here, this might have been caused by remote repository maintenance we were doing around the time the job was running, as we changed how we were signing our packages. This should be resolved now, but if the CI is failing for whatever reason, just let me know!

**Comment by orowith2os** [comment]
I've updated the docker image, so hopefully the issue is fixed. @89luca89 give it another try

**Comment by 89luca89** [comment]
> hm, I'm a bit interested in what the CI job is for. Is it just to test compatibility with distrobox, and make sure it works?

yep exactly that, it can check if one of my changes results in a break, or if images are having problems (especially EOL stuff where at one point the repos are unreachable)

> Hi, Project Lead of https://github.com/crystal-linux here, this might have been caused by remote repository maintenance we were doing around the time the job was running, as we changed how we were signing our packages. This should be resolved now, but if the CI is failing for whatever reason, just let me know!

Thanks for letting me know, is there a status page for this things so I can (for example) postpone a CI run if I see some work in progress like this?

Also i've tried again and it's still not working:

```sh
Packages (3) archlinux-keyring-20220727-1  crystal-keyring-20220729-1  pacman-6.0.1-7

Total Download Size:   2.01 MiB
Total Installed Size:  6.26 MiB
Net Upgrade Size:      0.02 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 archlinux-keyring-20220727-1-any downloading...
 pacman-6.0.1-7-x86_64 downloading...
 crystal-keyring-20220729-1-any downloading...
error: failed retrieving file 'crystal-keyring-20220729-1-any.pkg.tar.zst' from repo.getcryst.al : Connection timeout after 10000 ms
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
+ '[' 1 -ne 0 ']'
```

>  possibly fixed by updating everything rather than just those specific packages? 

it indeed does a complete update for arch family distros, so that's not a problem

---

Also my proposal would be to wait a bit more before re-including it again and use this issue to keep track and solve the problems

**Comment by not-my-segfault** [comment]
This is really strange, I've just tested, and the package repositories are up-to-date with the newest keys. Building an ISO or installing to my machine from the repositories seems to work, are these CI jobs built up from scratch or do they keep packages cached?

**Comment by 89luca89** [comment]
> This is really strange, I've just tested, and the package repositories are up-to-date with the newest keys. Building an ISO or installing to my machine from the repositories seems to work, are these CI jobs built up from scratch or do they keep packages cached?

That wasn't on a CI job, it was on my machine with a freshly pulled image

**Comment by orowith2os** [comment]
Tested on Distrobox, it updates without any issues. I'd chalk it up to a package (sudo) being corrupted as it reaches your machine, although it's a bit weird. Probably best to keep it out of the container distros list for now, at least until this is figured out, yeah

**Comment by orowith2os** [comment]
Correction: it works if I update from an already installed container. So definitely reproducible:

```looking for conflicting packages...

Packages (14) bc-1.07.1-4  curl-7.84.0-2  diffutils-3.8-1  findutils-4.9.0-1  fish-3.5.1-1  less-1:590-1  ncurses-6.3-3  pinentry-1.2.0-1  procps-ng-3.3.17-1  shadow-4.11.1-1  sudo-2.0-1  util-linux-2.38-1  vte-common-0.68.0-2  wget-1.21.3-1

Total Download Size:    7.13 MiB
Total Installed Size:  51.39 MiB
Net Upgrade Size:       0.19 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 util-linux-2.38-1-x86_64 downloading...
 shadow-4.11.1-1-x86_64 downloading...
 ncurses-6.3-3-x86_64 downloading...
 curl-7.84.0-2-x86_64 downloading...
 procps-ng-3.3.17-1-x86_64 downloading...
 findutils-4.9.0-1-x86_64 downloading...
 pinentry-1.2.0-1-x86_64 downloading...
 less-1:590-1-x86_64 downloading...
 bc-1.07.1-4-x86_64 downloading...
 vte-common-0.68.0-2-x86_64 downloading...
checking keyring...
checking package integrity...
error: sudo: signature from "Build-A-Package Workshop 2: Electric Boogaloo (Beep2 Boop2!) <null@getcryst.al>" is invalid
:: File /var/cache/pacman/pkg/sudo-2.0-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
error: failed to commit transaction (invalid or corrupted package)
Do you want to delete it? [Y/n]
Errors occurred, no packages were upgraded.
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred```

**Comment by orowith2os** [comment]
Fixed by repackaging `sudo`, seems to just have been a corrupted package.
![](https://cdn.discordapp.com/attachments/843147448917950485/1002725268202471504/unknown.png)

**Comment by 89luca89** [comment]
@orowith2os is the image on dockerhub updated already? I've just tried again and seems like the problem persists on the hosted image

![image](https://user-images.githubusercontent.com/598882/181896231-76ff1444-7f13-453e-b819-2534133263e4.png)
![image](https://user-images.githubusercontent.com/598882/181896317-9aa7238b-be1a-4201-b6ab-df7b1d007c4e.png)

**Comment by orowith2os** [comment]
Ah, mb, I didn't update the image. Should be good to go now.

**Comment by 89luca89** [comment]
Just pulled the latest image and it still does not work

```
:: File /var/cache/pacman/pkg/sudo-2.0-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
error: sudo: signature from "Build-A-Package Workshop 2: Electric Boogaloo (Beep2 Boop2!) <null@getcryst.al>" is invalid
error: failed to commit transaction (invalid or corrupted package)
Do you want to delete it? [Y/n] 
Errors occurred, no packages were upgraded.
Error: An error occurred
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
```

seems like the latest image on dockerhub is 

```
docker.io/crystallinux/crystal  latest      e87a3ae12db7  5 days ago  1.06 GB
```

So something wrong with this
I'll keep all of this in wait for the future, when everything will be fixed, we can re-evaluate the inclusion

**Comment by not-my-segfault** [comment]
We've resolved the `sudo` package signing issue now, an `asciinema` of everything working included (way too large for a big screenshot)
https://asciinema.org/a/yavTjRdEXDwYr26v3Vyfn1Yhd

Not sure what the issue with dockerhub is, I'll look into it and keep this thread posted

**Comment by 89luca89** [comment]
This has already been implemented
