### ISSUE TITLE
[Error] stats is not supported in rootless mode without cgroups v2

### ISSUE THREAD

**Issue by Ferenc-** [89luca89/distrobox#929]
Please, before opening a bug:

- [x] make sure you've read the documentation.
- [x] Ensure there isn't already an open issue about this.
- [x] Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**

`distrobox list` doesn't show anything useful except `Error: stats is not supported in rootless mode without cgroups v2`.

**To Reproduce**
1. Get a RedHat 8.8 host
2. Ensure Podman `4.4.1` installed.
3. Install latest `distrobox` `1.5.0.2`.
4. Create some distroboxes: `distrobox create --name test --image archlinux:latest`
5. Run `distrobox list`

**Expected behavior**
`distrobox list` shows something useful.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

[distrobox.log](https://github.com/89luca89/distrobox/files/12388191/distrobox.log)

**Desktop (please complete the following information):**
 - Are you using podman or docker? -> `podman`
 - Which version or podman or docker? -> `4.4.1`
 - Which version of distrobox? -> `1.5.0.2`

**Additional context**
Kernel version: `4.18.0-477.13.1.el8_8.x86_64`

**Comment by 89luca89** [comment]
This has been resolved in latest version (in git) by removing the stats completely

**Comment by sunarowicz** [comment]
I still have this issue unfortunately.
Host architecture: arm64
distrobox: 1.5.0.2

This issue appears after creating the amd64 container this way:
```
tux@rock5b ~> podman pull --arch=amd64 ubuntu
Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/shortnames.conf)
Trying to pull docker.io/library/ubuntu:latest...
Getting image source signatures
Copying blob aece8493d397 done  
Copying config e4c5895818 done  
Writing manifest to image destination
Storing signatures
e4c58958181a5925816faa528ce959e487632f4cfd192f8132f71b32df2744b4

tux@rock5b ~> distrobox create -i ubuntu -n ubuntu-amd64
Creating 'ubuntu-amd64' using image ubuntu       [ OK ]
Distrobox 'ubuntu-amd64' successfully created.
To enter, run:

distrobox enter ubuntu-amd64

tux@rock5b ~> distrobox ls
ID           | NAME                 | STATUS             | MEM              | CPU%  | IMAGE                         
Error: stats is not supported in rootless mode without cgroups v2
tux@rock5b ~ [125]>
```
Any idea?
