### ISSUE TITLE
[Discussion] `Error: could not find a supported package manager`

### ISSUE THREAD

**Issue by worldofgeese** [89luca89/distrobox#986]
I've created two different distroboxes, one with fedora-38 and another with bazzite-arch on Guix System as a host. What I don't understand is this error message as I can only assume it should be calling any supported package manager inside the container and not on the host?

Error follows:

```console
~ → distrobox enter bazzite-arch-latest
Container bazzite-arch-latest is not running.
Starting container bazzite-arch-latest
run this command to follow along:

 /gnu/store/nh3ri988gf5xbvyk9xpq8zqdhm0l601f-podman-4.4.1/bin/podman logs -f bazzite-arch-latest

 Error: could not start entrypoint.
+ '[' -n '' ']'
+ printf 'distrobox: Installing basic packages...\n'
++ basename /gnu/store/m6c5hgqg569mbcjjbp8l8m7q82ascpdl-bash-5.1.16/bin/bash
+ shell_pkg=bash
+ '[' bash = ash ']'
+ '[' 0 -ne 0 ']'
+ test -x find
+ test -x apk
+ test -x apt-get
+ test -x dnf
+ test -x emerge
+ test -x microdnf
+ test -x pacman
+ test -x slackpkg
+ test -x swupd
+ test -x xbps-install
+ test -x yum
+ test -x zypper
+ printf 'Error: could not find a supported package manager.\n'
+ printf 'Error: could not set up base dependencies.\n'
+ exit 127
+ '[' 127 -ne 0 ']'
+ printf 'Error: An error occurred\n'
distrobox: Installing basic packages...
Error: could not find a supported package manager.
Error: could not set up base dependencies.
Error: An error occurred
```

**Comment by 89luca89** [comment]
Seems more like a problem on the container image?

Anyway Guix is not one of the system I support nor test so I can't accept the bug report
You should report this to your distro mantainer

**Comment by worldofgeese** [comment]
Hey there! I tagged this as a discussion, not a bug report. to avoid burdening you with needing to provide a solution or anything at all really, other than a theory, if you had one. Just asking a question especially to folks who may currently be using Guix System or who may have in the past. Apologies if I misused the tag.

**Comment by dev590t** [comment]
about the error `Error: could not find a supported package manager.` Guix package manager install a outdated version of distrobox 1.5.0.2. The last version of distrobox should solve the issue if you configure the distrobox correctly using podman.

**Comment by jakiki6** [comment]
I bumped my locally installed version to 1.6.0.1 but I still get the same issue

```
bash-5.1$ distrobox --version
distrobox: 1.6.0.1
bash-5.1$ distrobox enter test4
 Error: could not start entrypoint.
+ stat /run/host/etc/shadow
++ stat -c %u /run/host/etc/shadow
+ '[' 65534 = 0 ']'
+ '[' -n '' ']'
+ printf 'distrobox: Installing basic packages...\n'
++ basename zsh
+ shell_pkg=zsh
+ '[' zsh = ash ']'
+ missing_packages=0
+ dependencies='
        bc
        bzip2
        chpasswd
        curl
        diff
        find
        findmnt
        gpg
        hostname
        less
        lsof
        man
        mount
        passwd
        pigz
        pinentry
        ping
        ps
        rsync
        script
        ssh
        sudo
        time
        tree
        umount
        unzip
        useradd
        wc
        /gnu/store/a36b37hn00gp8882rgiqb3ihrb8dl6g4-wget-1.21.3.24/bin/wget
        xauth
        zip
        zsh
'
+ for dep in ${dependencies}
+ test -x bc
+ missing_packages=1
+ break
+ '[' 0 -ne 0 ']'
+ '[' 1 -ne 0 ']'
+ test -x apk
+ test -x apt-get
+ test -x dnf
+ test -x emerge
+ test -x microdnf
+ test -x pacman
+ test -x slackpkg
+ test -x swupd
+ test -x xbps-install
+ test -x yum
+ test -x zypper
+ printf 'Error: could not find a supported package manager.\n'
+ printf 'Error: could not set up base dependencies.\n'
+ exit 127
+ '[' 127 -ne 0 ']'
+ printf 'Error: An error occurred\n'
+ stat /run/host/etc/shadow
++ stat -c %u /run/host/etc/shadow
+ '[' 65534 = 0 ']'
+ '[' -n '' ']'
+ printf 'distrobox: Installing basic packages...\n'
++ basename zsh
+ shell_pkg=zsh
+ '[' zsh = ash ']'
+ missing_packages=0
+ dependencies='
        bc
        bzip2
        chpasswd
        curl
        diff
        find
        findmnt
        gpg
        hostname
        less
        lsof
        man
        mount
        passwd
        pigz
        pinentry
        ping
        ps
        rsync
        script
        ssh
        sudo
        time
        tree
        umount
        unzip
        useradd
        wc
        /gnu/store/a36b37hn00gp8882rgiqb3ihrb8dl6g4-wget-1.21.3.24/bin/wget
        xauth
        zip
        zsh
'
+ for dep in ${dependencies}
+ test -x bc
+ missing_packages=1
+ break
+ '[' 0 -ne 0 ']'
+ '[' 1 -ne 0 ']'
+ test -x apk
+ test -x apt-get
+ test -x dnf
+ test -x emerge
+ test -x microdnf
+ test -x pacman
+ test -x slackpkg
+ test -x swupd
+ test -x xbps-install
+ test -x yum
+ test -x zypper
+ printf 'Error: could not find a supported package manager.\n'
+ printf 'Error: could not set up base dependencies.\n'
+ exit 127
+ '[' 127 -ne 0 ']'
+ printf 'Error: An error occurred\n'
+ stat /run/host/etc/shadow
++ stat -c %u /run/host/etc/shadow
+ '[' 65534 = 0 ']'
+ '[' -n '' ']'
+ printf 'distrobox: Installing basic packages...\n'
++ basename zsh
+ shell_pkg=zsh
+ '[' zsh = ash ']'
+ missing_packages=0
+ dependencies='
        bc
        bzip2
        chpasswd
        curl
        diff
        find
        findmnt
        gpg
        hostname
        less
        lsof
        man
        mount
        passwd
        pigz
        pinentry
        ping
        ps
        rsync
        script
        ssh
        sudo
        time
        tree
        umount
        unzip
        useradd
        wc
        /gnu/store/b1dc9qrjaq1gdbrjwjg4z8xxqd6c5kp2-wget-1.21.3.24/bin/wget
        xauth
        zip
        zsh
'
+ for dep in ${dependencies}
+ test -x bc
+ missing_packages=1
+ break
+ '[' 0 -ne 0 ']'
+ '[' 1 -ne 0 ']'
+ test -x apk
+ test -x apt-get
+ test -x dnf
+ test -x emerge
+ test -x microdnf
+ test -x pacman
+ test -x slackpkg
+ test -x swupd
+ test -x xbps-install
+ test -x yum
+ test -x zypper
+ printf 'Error: could not find a supported package manager.\n'
+ printf 'Error: could not set up base dependencies.\n'
+ exit 127
+ '[' 127 -ne 0 ']'
+ printf 'Error: An error occurred\n'
+ stat /run/host/etc/shadow
++ stat -c %u /run/host/etc/shadow
+ '[' 65534 = 0 ']'
+ '[' -n '' ']'
+ printf 'distrobox: Installing basic packages...\n'
++ basename zsh
+ shell_pkg=zsh
+ '[' zsh = ash ']'
+ missing_packages=0
+ dependencies='
        bc
        bzip2
        chpasswd
        curl
        diff
        find
        findmnt
        gpg
        hostname
        less
        lsof
        man
        mount
        passwd
        pigz
        pinentry
        ping
        ps
        rsync
        script
        ssh
        sudo
        time
        tree
        umount
        unzip
        useradd
        wc
        /gnu/store/b1dc9qrjaq1gdbrjwjg4z8xxqd6c5kp2-wget-1.21.3.24/bin/wget
        xauth
        zip
        zsh
'
+ for dep in ${dependencies}
+ test -x bc
+ missing_packages=1
+ break
+ '[' 0 -ne 0 ']'
+ '[' 1 -ne 0 ']'
+ test -x apk
+ test -x apt-get
+ test -x dnf
+ test -x emerge
+ test -x microdnf
+ test -x pacman
+ test -x slackpkg
+ test -x swupd
+ test -x xbps-install
+ test -x yum
+ test -x zypper
+ printf 'Error: could not find a supported package manager.\n'
+ printf 'Error: could not set up base dependencies.\n'
+ exit 127
+ '[' 127 -ne 0 ']'
+ printf 'Error: An error occurred\n'
distrobox: Installing basic packages...
Error: could not find a supported package manager.
Error: could not set up base dependencies.
Error: An error occurred
distrobox: Installing basic packages...
Error: could not find a supported package manager.
Error: could not set up base dependencies.
Error: An error occurred
distrobox: Installing basic packages...
Error: could not find a supported package manager.
Error: could not set up base dependencies.
Error: An error occurred
distrobox: Installing basic packages...
Error: could not find a supported package manager.
Error: could not set up base dependencies.
Error: An error occurred
```

**Comment by dev590t** [comment]
@jakiki6 
```
dev_1@localhost ~$ cat ${HOME}/.config/distrobox/distrobox.conf
container_always_pull="1"
container_generate_entry=0
container_manager="podman"
container_image_default="registry.opensuse.org/opensuse/toolbox:latest"
container_name_default="test-name-1"
non_interactive="1"
skip_workdir="0"

dev_1@localhost ~$ distrobox --version
distrobox: 1.6.0.1
dev_1@localhost ~$ distrobox create -n test
Distrobox named 'test' already exists.
To enter, run:

distrobox enter test

dev_1@localhost ~$ distrobox enter test
dev_1@test ~$ 
```

The error is raise from https://github.com/89luca89/distrobox/blob/55052318202388ac17886f4e8cc12ed93d13ae0d/distrobox-enter#L485

I think you can manual execute the [code](https://github.com/89luca89/distrobox/blob/55052318202388ac17886f4e8cc12ed93d13ae0d/distrobox-enter#L481) to see what is the problem. It seem your container manager doesn't run correctly.

This is my result:
```
$ podman inspect --type container "test" --format "{{.State.Status}}"
running

```
run podman on guix need some configuration. You can try `container_manager="docker"` rather
